### ISSUE TITLE
New View: Landing Page

### ISSUE THREAD

**Issue by herzogrh** [citysciencelab/scenario-explorer-addon#21]
There should be a landing page to which the user is redirected after being logged in. The landing page should contain a welcome message, an overview of the most recent scenarios and ensembles the user was working on, as well as a refernce to the help-section of the tool.

**Comment by FritzHoing** [comment]
Currently, all available scenarios and jobs are displayed on the landing page for the user. If only the ones the user has worked on should be shown, this is would still be an open ToDo.
