### ISSUE TITLE
New view: Help section

### ISSUE THREAD

**Issue by herzogrh** [citysciencelab/scenario-explorer-addon#22]
There should be a help section in which users can see some documentation of the tool and be able to see help pages / tutorials. There could also eg. be an FAQ.

**Comment by verendi** [comment]
@herzogrh : Should the content for the help section be taken out of the mockups?

**Comment by FritzHoing** [comment]
Implemented via the welcome page MR: https://github.com/citysciencelab/scenario-explorer-addon/pull/30
