### ISSUE TITLE
Masterportal 3 Migration

### ISSUE THREAD

**Issue by herzogrh** [citysciencelab/scenario-explorer-addon#5]
Migrate the codebase to work as a [Masterportal 3 ](https://www.masterportal.org/news/detail/masterportal-300-release-am-28062024) AddOn

**Comment by FritzHoing** [comment]
Solved in:
- https://github.com/citysciencelab/scenario-explorer-addon/pull/1
- https://github.com/citysciencelab/scenario-explorer-addon/pull/2
- https://github.com/citysciencelab/scenario-explorer-addon/pull/3
