### ISSUE TITLE
New view: Overview page of own and shared scenarios 

### ISSUE THREAD

**Issue by herzogrh** [citysciencelab/scenario-explorer-addon#7]
The addon should contain a new view that displays all job results available to the user (both own jobs/job ensembles and jobs/job ensembles shared with the user). The job results should be queryable and filterable by model, date, name, ensemble or user.

**Comment by KaiVolland** [comment]
IMHO this covered by the `JobList` component.

![image](https://github.com/user-attachments/assets/c4185eb9-6cfc-439a-a896-fb9497d5badd)
